<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit5dd2bcd33707ad3654caeb1d6ecaae61
{
    public static $prefixesPsr0 = array (
        'Zy'        => BASEPATH . '/',
        'Service'   => APPPATH . '/' . 'models' . '/',
        'Dao'       => APPPATH . '/' . 'models' . '/',
        'Twig'      => SYSPATH . '/' . 'library' . '/',
        'Alipay'    => SYSPATH . '/' . 'library' . '/' . 'pay' . '/',
        'Wxpay'     => SYSPATH . '/' . 'library' . '/' . 'pay' . '/',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            ComposerStaticInit5dd2bcd33707ad3654caeb1d6ecaae61::$prefixesPsr0[ucfirst(APP_NAME)] = APPPATH . '/' . 'library' . '/';
            $loader->prefixesPsr0 = ComposerStaticInit5dd2bcd33707ad3654caeb1d6ecaae61::$prefixesPsr0;
        }, null, ClassLoader::class);
    }
}
